// Otomatik üretildi: Hidrolik Excel görünür belgelerinden çıkarıldı. Elle düzenlenebilir.

export const KULLANIM_KLAVUZU_HID: string[] = [
  "Binalarda insanların ve/veya yüklerin bir kabin içerisinde bir duraktan diğerine dikey doğrultuda taşımak için üretmiş olduğumuz bu asansör talimatlara uyularak kullanıldığı zaman tamamen güvenli bir taşıma aracıdır. Asansörü kullanmadan önce kullanma kılavuzu dikkatlice okunup anlaşılmalıdır. Anlaşılmayan veya belirtilmeyen bir konu olduğunda mutlaka firmamız ile irtibat kurulmalıdır.",
  "Bu kılavuz, kullanıcıların can güvenliklerinin sağlanması ve asansörlerin kullanım ömürlerinin en üst düzeyde tutulabilmesi için asansörün kullanımı, bakımının yapılması, arıza, tamir ve ayarlarının yapılması ile muayene ve acil durumlar esnasında uyulması gereken kuralları belirtir. İlgili Kanun ve Yönetmelikler; • Asansör İşletme ve Bakım Yönetmeliği (06.04.2019 Tarih ve 30737 sayılı resmi gazete) • Asansör Yönetmeliği 2014/33 AB Asansör Yönetmeliği",
  "• Asansör Montaj Firması: Asansörlerin tasarım, imalat, montaj ve piyasaya arzından sorumlu olan, asansöre CE uygunluk işaretini iliştiren ve AB uygunluk beyanı düzenleyen gerçek veya tüzel kuruluşlardır. • Bina Sorumlusu: Asansörün, güvenli bir şekilde çalışmasını sağlamak amacıyla düzenli olarak bakımını, onarımını ve yıllık kontrolünü yaptırmaktan sorumlu olan, binanın maliki veya kat maliki/malikleri veya bunların yetki verdiği gerçek veya tüzel kişilerdir. • Yetkili Servis: Asansör monte edenin, asansörlerin bakım hizmetlerini yürütmek için; sorumluluğu kendinde olmak üzere noter huzurunda yapılan sözleşme ile yetki verdiği “TSE Hizmet Yeterlilik Belgesi”ne sahip gerçek veya tüzel kuruluşlardır. • Yıllık Kontrol: Asansörün, güvenli ve işletme yönünden uygun şekilde çalıştığının tespiti için, hizmete alınmasını müteakip iki yıl sonra, devamında yılda en az bir kere bina sorumlusu tarafından, asansörün bulunduğu belediye başvurularak yaptırılacak kontrolüdür.",
  "Kat Göstergesi ( Kabinin hangi katta olduğunu belirtir.)",
  "(Varsa) Aşağı / Yukarı Yön Butonu ( Yalnızca gitmek istediğiniz yöne basınız.)",
  "Meşgul Butonu (Bu buton yanıyorsa asansörün meşgul olduğunu gösterir.)",
  "Kabin Katta Butonu (Bu buton yanıyorsa asansör kabinin o katta olduğunu gösterir.)",
  "Servis Dışı Butonu ( Bu buton yanıyor ise asansörün kullanılamayacağını belirtir.)",
  "(Varsa) Çağır Butonu ( Asansörü bulunduğunuz kata çağırmak için kullanılır.)",
  "1- Kabinin hangi katta olduğunu kat göstergesinden takip edebilirsiniz.",
  "2- Hangi kat ve doğrultuya gitmek istediğinizi belirledikten sonra, “varsa” aşağı/yukarı yön butonuna veya",
  "çağırma butonuna “ Ç “ basınız.",
  "3- Kabinden çıkmak isteyenlerin geçiş yolu üzerinde durmayınız, geçişe engel olmayacak bir yerde bekleyiniz.",
  "4- Asansör yarım otomatik ise kapı kolundan tutarak kapıyı çekiniz. Kabin içinde yolcu varsa kapıyı açmaya çalışacağını unutmayıp kapının size çarpmayacağı bir yerde bekleyiniz. Asansör tam otomatik bir asansör ise bekleyiniz kapı otomatik olarak açılacaktır.",
  "5- Asansör beklediğiniz kata geldiğinde, asansörün dolu olması halinde mutlaka kabine girmeye çalışmayınız, asansörün tekrar bulunduğunuz kata gelmesini bekleyiniz, (varsa) diğer asansörü kullanınız.",
  "6- Otomatik kapılı asansörlerde, kapısı kapanmakta olan asansörün kapısını açmaya çalışmayınız, asansörün tekrar bulunduğunuz kata gelmesini bekleyiniz, (varsa) diğer asansörü kullanınız.",
  "Kabin İçi Display ( Asansörün seyir halinde hangi kata olduğunu ve gittiği yönü gösterir.)",
  "Kat Butonları ( Gidilmek istenen katın butonuna basınız.)",
  "Aşırı Yük İkaz Lambası ( Asansörün taşıma kapasitesinin aşılması durumunda yanar. Asansör hareket etmez.)",
  "Kapı Kapama Butonu ( Kabin kapısının kapanmasını sağlar.)",
  "Kapı Açma Butonu ( Kabin kapısının açılmasını sağlar.)",
  "Acil Aydınlatma Lambası ( Elektrik kesilmesi gibi acil durumlarda kabinin aydınlatılmasını “5 lux” sağlar.)",
  "Diafon Butonu ( Acil durumlarda kabin dışı ile irtibat sağlanması için kullanılır.)",
  "İmdat Butonu ( Acil durumlarda basılarak sesli ikaz verilebilir.)",
  "Fan Butonu ( Suni havalandırma yapılan asansörlerde, kabinin havalandırılması içi kullanılır.)",
  "Kabin ve Kat Etiketleri",
  "Kat etiketi olup hangi katta bulunduğunuzu gösterir.",
  "Asansöre bakım yapıldığında bu etiket kullanılır. Bu etiketi görüldüğünde asansör kullanılamaz.",
  "Makine dairesini gösterir. Yetkili olmayanların girmesi tehlikeli ve yasaktır.",
  "Asansörlerde asansörün taşıyabileceği maksimum kişi veya kapasiteyi belirtir.",
  "Kullanılan halatın teknik özelliklerini ve işletmeye konulduğu tarihi yazar.",
  "Asansörünüzün, Avrupa Birliği Normlarına uygun olarak imal edildiğini gösterir. Bu etiketin kabin içinde bulunması zorunludur.",
  "Asansörü imal eden firma bilgilerini, yapım yılını, hızını ve asansörün seri no.sunu gösterir etikettir.",
  "5 ASANSÖR SAHİBİNİN SORUMLULUKLARI",
  "* Bina sorumlusu, asansörün güvenli bir şekilde çalışmasını sağlamak üzere bakımını yaptırmaktan ve bakım ücretinin ödenmesinden sorumludur.",
  "* Bina sorumlusu, engellilerin erişilebilirliği için asansörün güvenli bir şekilde sürekli olarak çalıştırılmasını sağlar. Kamuya açık alanlarla ilgili olarak birinci cümlede belirtilen konuya ilişkin şikâyetler ilgisi nedeniyle Valilik bünyesinde bulunan erişilebilirlik izleme ve denetleme komisyonuna, konutlarla/meskenlerle ilgili şikâyetler ise konutun/meskenin bağlı bulunduğu ilgili idaresine iletilir.",
  "* Bina sorumlusu, asansörle ilgili herhangi bir tehlikeli durumu bakım sözleşmesi imzalanan asansör monte eden veya onun yetkili servisine iletir ve söz konusu asansöre, asansör monte eden veya onun yetkili servisi tarafından müdahale edilene kadar gerekli güvenlik tedbirini alır.",
  "6 KULLANMA TALİMATLARI",
  "• Makine dairesinin kapısının kilitli tutulması; Asansör makine dairesinde bulunan makine ve elektrik aksamlarını dışarıdan gelebilecek doğal etkenlere karşı korumak amacıyla, makine dairesi kapısı sürekli kilitli tutulacaktır. Makine dairesi kilit anahtarı bina yönetimini haricinde kimsede bulundurulmayacak ve asansör bakımını yapan firma çalışanları veya yetkilileri haricinde kimseye verilmeyecektir.",
  "• Makine Dairesi Kullanımı; Makine veya makara dairelerinde asansör makineleri haricinde asansör makine ve makaraların çalışmasını engelleyecek şekilde, hiçbir eşya, cihaz, alet v.s bulundurulmayacaktır. Bakımcı Firma tarafından ya da yapılan bakım anlaşmasına göre yönetim tarafından, makine dairelerinde her zaman bakım malzemesi (yağ, üstübü, mazot, gres yağ vs.) makine dairesinde uygun yerlerde bulundurulacaktır.",
  "• Güvenli yükleme ve boşaltma; Belirtilen beyan yükünden fazla yükleme yapılmayacaktır. Asansör kabini görmeden kabine girilmemelidir. Asansöre girerken ve çıkarken kapılar iyice kapatılacaktır. Asansör kat seviyesinde durmadan önce kapıları açıp çıkmayınız.",
  "• Asansör kuyusu tamamen kapalı durumdadır.",
  "• Yetkili kişilerin müdahalesini gerektiren olaylar; Asansörün arıza yapması durumunda arıza, en kısa zamanda bakımcı firmaya bildirilmelidir.",
  "• Asansörün Kullanımı;",
  "1- Asansöre binmeden ve/veya yükleme yapmadan önce kabinin katta olduğundan emin olunuz.",
  "2- Asansöre binip, inerken ve/veya yüklerin indirilip/yüklenmesinde dikkatli olunuz. Asansör ve kat seviyesi farklılıkları olabilir, takılıp düşebilirsiniz.",
  "3- Kabin kasetindeki aşırı yük ikaz lambasının yanmadığından emin olun; eğer yanıyorsa asansörden hızlı hareketlerle ininiz.",
  "4- Gideceğiniz kata karar verip; şekilde gösterilen kabin kasetinde uygun kat düğmesine basınız.",
  "5- Asansörün geldiği kata, kabin içi kat göstergesinden bakarak, gitmek istediğiniz kat olduğunu doğruladıktan sonra ininiz.",
  "6- Çocukları, evcil hayvanları (kedi köpek vs.), kontrol altında tutunuz veya yüklerin güvenli yüklendiğinden emin olunuz.",
  "7- Otomatik kapılı asansörlerde, kapının açılması bir açma butonu aracılığıyla oluyorsa, kapıyı butonuna basarak açınız. Kabin katta durmadan kapıyı açmaya çalışmayınız.",
  "8- Kabine girerken ve kabinden çıkarken oyalayıcı hareketlerden kaçınınız.",
  "9- Kabinde tutamak (küpeşte) varsa tutunuz.",
  "10- Kat göstergelerine dikkat ediniz ve izleyiniz.",
  "11- Asansörün durmasına karşın, otomatik kabin kapılı asansörlerde kapı açma butonu ile de kapı açılamıyorsa veya asansör kat arasında kalırsa kesinlikle paniğe kapılmayınız.",
  "12- Böyle bir durumda imdat butonu ve / veya diafon butonunu kullanarak dışarıdaki kişilerle irtibata geçiniz.",
  "13- Elektrik kesilmesi sonucu kabin içinde kalınırsa yine imdat ve diafon butonunu kullanabilirsiniz. (İmdat ve diafon beslemesi şebeke geriliminden ayrı bir kaynaktandır.)",
  "14- Yukarıda belirtilen durumlar dışında gereksiz yere seyir halindeyken stop ve imdat butonuna basmayınız ve çocukların basmamasını sağlayınız.",
  "15- Asansör seyir halindeyken kabin kapısını açmaya çalışmayınız.",
  "1- Asansör içinde iki kat arasında kalan kişilerin kurtarılmasında kapı kilit anahtarının kullanılması tehlikeli olduğundan, kurtarma işlemi hidrolik ünite grubu üzerindeki acil iniş valf grupları yardımıyla yapılmalıdır.",
  "2- Makine dairesi kapısı veya giriş kapağı güvenlik nedeniyle sürekli kilitli tutulmalı, ancak her hangi bir nedenle içeri girilmesi gerektiğinde anahtar bina yöneticisi ve görevlisi ile belirlenecek kişilerde bulunmalıdır.",
  "3- Kuyu boşluğuna kâğıt ve benzeri yanıcı maddelerin atılması önlenmeli, buradan başlayacak bir yangın kısa sürede kabini etkileyeceği göz önünde bulundurulmalıdır.",
  "4- Kabin girişine konulan fotosel ya da eşik kontağı gibi güvenlik tertibatları ( Kapı sıkışmalarını engellemek için) mutlaka çalışır durumda tutulmalı, özellikle çocukların bunlarla oynamaları, bozmaları önlenmeli ve uyarılmalıdır.",
  "5- Kat kapı camları telli dahi olsa el ve parmak girecek kadar açıklık olduğunda cam değiştirilinceye kadar güvenlik nedeniyle asansör işletmeye kapatılmalıdır.",
  "6- Makine dairesi depo olarak kullanılmamalıdır. Asansör ile ilgili teçhizatlar haricinde makine dairesinde başka teçhizatlar bulundurulmamalıdır. ( uydu anteni ekipmanları vb.)",
  "7- Makine dairesinde bulunan havalandırma pencereleri ile varsa kapılar uygun bir havalandırma sağlanması için panjurlu hale getirilmelidir.",
  "8- Makine dairesindeki aydınlatma tesisatı çalışır durumda bulundurulmalıdır.",
  "9- Makine dairesine kolayca görülebilecek bir yere kurtarma talimatı asılmalıdır. Kabin içinde bulunan imdat butonu özellikle elektrik kesilmeleri ve arıza durumunda kullanılması gerektiğinden acil aydınlatma kaynağından beslenmesi sağlanmalıdır.",
  "10- Asansör kabinin katta olduğunu anlamak için kabin içinde mutlaka sürekli aydınlatma sağlanmalıdır.",
  "11- Kabin içi güvenlik kapısı kılavuzları içinde pislik birikmesi engellenmelidir.",
  "12- Merdiven temizliği yapılırken kuyu dibine su girmesi önlenmelidir.",
  "13- Tehlike anında İMDAT butonlarına basılmalı, her iki butonun gereksiz kullanılmaları önlenmelidir.",
  "14- Bir yangın, deprem vs. gibi doğal afet anında kaçış için asansör kullanılmamalıdır.",
  "15- Asansöre 12 yaşından küçük çocukların yalnız başına binmeleri yasaktır.",
  "8 KULLANIM HATALARI İÇİN BİLGİ",
  "1- Asansör için tasarlanan insan sayısından fazla kişi asansöre binmemelidir.",
  "2- Sadece yük taşınacak asansörler yük ile birlikte asansöre insan binmemelidir.",
  "3- İnsan taşımak için tasarlanmış asansörlerde yük veya eşya taşınmamalıdır.",
  "4- Kremayer iç kapılı asansörlerde kabin içinde girişe yakın durulmamasına dikkat edilmelidir.",
  "5- Kat butonu üzerindeki yön butonlarından sadece gideceğiniz yöndeki (yukarı veya aşağı ) butona basılmalıdır.",
  "6- Meşgul lambası yanıyorken çağırma butonuna basılmamalıdır.",
  "7- Emniyet açısından asansöre girip çıkarken oyalanılmamalıdır.",
  "9 YETKİLİ KİŞİLERİN MÜDAHALESİNİ GEREKTİREN DURUMLAR",
  "Aşağıda belirtilen durumlar ile karşılaşılması halinde, mutlaka sözleşmeli olduğunuz bakım servisi veya bina sorumlusu ile irtibata geçiniz. Kendi başınıza müdahale etmeyiniz. 1- Asansörün kat arasında arızalanması. 2- Asansörün hareket etmemesi. 3- Asansör motorunun çalışmaması. 4- Arızalanan asansörde mahsur kalan kişilerin kurtarılma ihtiyacı. 5- Her hangi bir imdat çağrısı yapılması. 6- Elektrik kesintisi sonucu arıza. 7- “Kapı Kilit Açma Anahtarı”nın kullanılması gereken durumlar.",
  "1- Asansör, elektrik kesintisi veya arıza gibi nedenlerden kabini iki kat arasında kalabilir. Asansörünüz tasarım ve montaj aşamasında bu tür riskli durumlar düşünülerek her türlü önlem alınmıştır.",
  "2- Periyodik bakımları düzenli ve bilinçli yapılan asansörümüzde bu durumlar hayati risk içermez. Kurtarma gibi önemli ve riskli olabilecek durumlarda “asansör firması” çağırılmalıdır.",
  "3- Kurtarma konusunda eğitim almış kişiler var ise kılavuzda ve makine dairesinde belirtilen kurtarma talimatına aynen uyulmalıdır. Bu talimatlarda kurtarma adım adım anlatılmıştır.",
  "4- Eğitim almış kişiler tarafından yapılan kurtarma işleminde belirtilen adımların dışında anormal bir durum gözlenir ise bu işleme devam edilmemeli ve mutlaka “Asansör Firması”na bildirilmeli ve daha profesyonel bir yardım alınmalıdır.",
  "5- Acil Durumda Makine Dairesinin Kullanımı Kabinde mahsur kalan kişilerin kurtarılması; (Şekil 1) Asansörün elektriğini ana elektrik panosunun üzerindeki ana şalteri \"0\" konumuna getirin. Makine dairesinde bulunan kurtarma talimatını inceleyin ve buna göre hareket edin. Talimatın anlatımına destek olarak aşağıdaki maddeleri uygulayın.",
  "ACİL DURUM KİLİT AÇMA ANAHTARININ KULLANIMI",
  "Tanım: Asansörün Kat Arasında kaldığı durumlarda, içerisindeki şahısları kurtarmak amaçlı yapılmış, kapı kilit sistemini açtırarak, kapının açılmasını sağlayan anahtardır a. Anahtarı Kullanmadan önce şebeke elektriği kapalı olsa dahi, asansörün elektriğini ana şalterden tamamen kapatın ve asansörün elektriğinin kapalı olduğundan emin olun. b. Kilit açma anahtarını kapı kasası üzerinde bulunan yuvarlak delik üzerine yerleştirin. c. Kapının durumuna göre anahtarı sağ veya sol yönünde çevirin ve elinizi sabit tutun. d. Diğer elinizi kapı tutamağından tutarak kapıyı açın. e. Tam Otomatik Kapılı Asansör Kapılarında ise, açma anahtarını açık konumda sabit tutmak koşulu ile otomatik kapıyı, kapı açıklığından tutarak kapı açılma yönüne doğru çekin. f. Kapıyı açtıktan sonra kabin içerisindeki şahsın güvenli bir şekilde dışarı çıkmasına özen gösterin ve şahıs dışarı çıkarken kapının kapanmaması için dikkatli bir şekilde kapıyı tutun. g. Kabin içindeki şahıslar çıktıktan sonra,kapının tamamen kapanmış ve kilitlenmiş olduğunu kontrol edin."
];

export const BAKIM_KLAVUZU_HID: string[] = [
  "1- Bina yönetimi, asansörün bakımını garanti kapsamı dahilinde ilk üç yıl montajı gerçekleştiren asansör firmasına, ondan sonraki yıllarda TSE Hizmet Yeterlilik Belgesine sahip olan asansör bakım firmalarına yaptırmalıdır. 2- Garanti süresi içinde bina yönetimi ile asansörün motajcısı veya onun yetkili servisi arasında aylık bakım sözleşmesi yapılması zorunludur. 3-Garanti süresi bitiminde bina yönetimi başka bir bakım firması ile çalışırsa montaj firması bakım talimatına uyulmalıdır. Aksi halde yanlış veya hatalı bakım sonucu oluşacak durumlardan montaj firması sorumlu değildir. 4- Bakımlar özel durum olmadığı takdirde bakım talimatında belirtilen şekilde yapılmalıdır. 5- Güvenlik ekipmanlarının bakım ve ayarları kullanma kılavuzlarına göre yapılmalıdır. 6- Bakıma başlanılmadan önce gerekli emniyet tedbirleri alınmalıdır. 7- Bütün kat kapılarına “Asansöre Bakım Yapılıyor” levhası asılmalıdır. 8- Makine ve elektrik aksamına ait bakım yapılırken ana şalter kapatılarak elektrik kesilmelidir. 9- Yapılan bakım asansör bakım defterine işlenmelidir. 10- Bakım esnasında bulunan uygunsuzluklar yazılı olarak bina yönetimine bildirilmelidir. Bakım yapan firmanın yazılı ihtarına rağmen uygunsuzluk giderilmediği taktirde sorumluluk bina yönetimine aittir. 11- İki kişiden az olmamak üzere binada bulunan kişilere acil durum kurtarma çalışması konusunda eğitim verilmelidir. Acil durum kilit açma anahtarı ( üçgeni ) tutanak ile eğitim alan kişilere teslim edilmelidir.",
  "Elektrikli Asansörlerin periyodik bakımlarının TS EN 13015 + A1 e uygun olarak yapılmasını sağlamak, arıza oranlarını azaltmak ve müşteri memnuniyetini sağlamak.",
  "2.1. Bakıma başlamadan önce emniyet tedbiri olarak, kat kapılarına “ASANSÖR BAKIMDA” levhası asılacak.",
  "2.2. Kumanda panosu, makine ve motorun bakımlarına başlamadan önce, termik şalterden elektrik kesilecek.",
  "2.3. Genel olarak bütün asansör parçalarının temizliğini, toz ve korozyon bulunup bulunmadığı kontrol edilecek.",
  "2.4. KUYU ALT BOŞLUĞU: * Kılavuz rayların altında yağ / gres yağı birikmiş mi kontrol edilir. * Kuyu alt boşluğunun temiz, kuru olduğunu ve inşaat vb. atıkların bulunmaması kontrol edilir.",
  "2.5 HİDROLİK ÜNİTE * Hidrolik sıvı seviyesi kontrol edilir. * Tank ve valf birimi sızıntı bakımından kontrol edilir. * Hareket süresi sınırlayıcı; Çalışma kontrol edilir.",
  "2.6. SIÇRAMAYA KARŞI TERTİBAT (varsa): * Serbest hareket ve çalışma kontrol edilir. * Halatlar eşit gerginlik bakımından kontrol edilir. * Anahtar, takıldığı yerde kontrol edilir. * Yağlama kontrol edilir.",
  "2.7. HİDROLİK TAMPONLAR (varsa): * Yağ seviyesi kontrol edilir. * Yağlama kontrol edilir. * Anahtar takıldığı yerde kontrol edilir. * Bağlantılar kontrol edilir.",
  "2.8 PİSTON * Yağ sızıntısı için kontrol yapılır. * Teleskopik pistonlarda senkronizasyon için kontrol yapılır.",
  "2.9. KUMANDA PANOSU: * Muhafaza temizliği, kuru olması ve toz bulunmaması bakımından kontrol edilir.",
  "2.10. HIZ REGÜLÂTÖRÜ ve GERME MAKARASI: * Hareketli bölümler rahat hareket ve aşınma bakımından kontrol edilir. * Çalışma kontrol edilir. * Anahtar kontrol edilir.",
  "2. 11. SAPTIRMA KASNAĞI ve MAKARALAR: * Durum ve aşınma bakımından yivler kontrol edilir. * Normal olmayan ses ve / veya titreşimler için rulmanlar kontrol edilir. * Muhafaza kontrol edilir. * Yağlama kontrol edilir.",
  "2.12. KABİN ve KARŞI AĞIRLIK RAYLARI: * Gerekli yerlerde bütün kılavuz yüzeyleri, üzerlerindeki yağ tabakası bakımından kontrol edilir. * Bağlantılar kontrol edilir. * Patenler; Kılavuz patenleri aşınma bakımından kontrol edilir. Bağlantılar kontrol edilir. Gerekli olan yerde yağlama kontrol edilir.",
  "2.13. ELEKTRİK TESİSATI: * Yalıtım kontrol edilir.",
  "2.14. KABİN: * Acil durum aydınlatması, asansör kabini düğmeleri, anahtarlar kontrol edilir. * Acil alarm tertibatı; Çalışma kontrol edilir. * Panellerin ve tavanın bağlantıları kontrol edilir.",
  "2.15. PARAŞÜT FRENLER: * Hareket eden bölümler serbest hareket olması ve aşınma bakımından kontrol edilir. * Yağlama kontrol edilir. * Bağlantılar kontrol edilir. * Çalışma kontrol edilir. * Anahtar kontrol edilir.",
  "2.16. ASKI HALATLARI: * Aşınma, uzama ve gerginlik bakımından kontrol yapılır. * Sadece gerekli yerde yağlama kontrol edilir. * Halat Şişeleri; Yıpranma ve aşınma için kontrol edilir. Bağlantılar kontrol edilir.",
  "2.17. DURAK KAPILARI: * Durak kilitlerinin çalışması kontrol edilir. * Rahat çalışma bakımından kapılar kontrol edilir. * Kapı kılavuzlanması kontrol edilir. * Kapı aralıkları kontrol edilir. * Tel halat, zincir veya kayış kullanıldığında, bunların uygunluğu kontrol edilir. * Acil kilit açma tertibatı kontrol edilir. * Yağlama kontrol edilir.",
  "2.18. KABİN KAPISI: * Kapı kapanma kontağı veya kilidi kontrol edilir. * Rahat hareket bakımından kapılar kontrol edilir. * Kapı kılavuzlanması kontrol edilir. * Kapı aralıkları kontrol edilir. * Tel halat, zincir veya kayış kullanıldığında, bunların uygunluğu kontrol edilir. * Yolcu kapısı koruma tertibatı kontrol edilir. * Yağlama kontrol edilir.",
  "2.19. KAT SEVİYELERİ: * Duraktaki duruş hassasiyeti kontrol edilir.",
  "2.20. SINIR GÜVENLİK KESİCİLER: * Çalışma kontrol edilir.",
  "2.21. ELEKTRİK GÜVENLİK TERTİBATI: * Çalışma kontrol edilir. * Elektrik güvenlik zinciri kontrol edilir. * Doğru sigortaların takıldığı kontrol edilir.",
  "2.22. DURAK KUMANDALARI ve GÖSTERGELER: * Çalışma kontrol edilir.",
  "2.23. KUYU AYDINLATMALARI: * Çalışma kontrol edilir.",
  "2.24. KAYMA DÜZELTME TERTİBATI: * Çalışma kontrol edilir.",
  "2.26. BASINÇ SINIRLAMA VALFİ: * Çalışma kontrol edilir.",
  "2.27. ELLE AŞAĞI HAREKET VALFİ: * Çalışma kontrol edilir.",
  "2.28. EL POMPASI: * Çalışma kontrol edilir.",
  "2.29. HORTUM / BORU SİSTEMİ: * Hasar ve sızıntı bakımından kontrol edilir."
];
