// Otomatik üretildi: Excel görünür belgelerinden çıkarıldı. Elle düzenlenebilir.

export const KULLANIM_KLAVUZU: string[] = [
  "Binalarda insanların ve/veya yüklerin bir kabin içerisinde bir duraktan diğerine dikey doğrultuda taşımak için üretmiş olduğumuz bu asansör talimatlara uyularak kullanıldığı zaman tamamen güvenli bir taşıma aracıdır. Asansörü kullanmadan önce kullanma kılavuzu dikkatlice okunup anlaşılmalıdır. Anlaşılmayan veya belirtilmeyen bir konu olduğunda mutlaka firmamız ile irtibat kurulmalıdır.",
  "Bu kılavuz, kullanıcıların can güvenliklerinin sağlanması ve asansörlerin kullanım ömürlerinin en üst düzeyde tutulabilmesi için asansörün kullanımı, bakımının yapılması, arıza, tamir ve ayarlarının yapılması ile muayene ve acil durumlar esnasında uyulması gereken kuralları belirtir. İlgili Kanun ve Yönetmelikler; • Asansör İşletme ve Bakım Yönetmeliği (06.04.2019 Tarih ve 30737 sayılı resmi gazete) • Asansör Yönetmeliği 2014/33 AB Asansör Yönetmeliği",
  "• Asansör Montaj Firması: Asansörlerin tasarım, imalat, montaj ve piyasaya arzından sorumlu olan, asansöre CE uygunluk işaretini iliştiren ve AB uygunluk beyanı düzenleyen gerçek veya tüzel kuruluşlardır. • Bina Sorumlusu: Asansörün, güvenli bir şekilde çalışmasını sağlamak amacıyla düzenli olarak bakımını, onarımını ve yıllık kontrolünü yaptırmaktan sorumlu olan, binanın maliki veya kat maliki/malikleri veya bunların yetki verdiği gerçek veya tüzel kişilerdir. • Yetkili Servis: Asansör monte edenin, asansörlerin bakım hizmetlerini yürütmek için; sorumluluğu kendinde olmak üzere noter huzurunda yapılan sözleşme ile yetki verdiği “TSE Hizmet Yeterlilik Belgesi”ne sahip gerçek veya tüzel kuruluşlardır. • Yıllık Kontrol: Asansörün, güvenli ve işletme yönünden uygun şekilde çalıştığının tespiti için, hizmete alınmasını müteakip iki yıl sonra, devamında yılda en az bir kere bina sorumlusu tarafından, asansörün bulunduğu belediye başvurularak yaptırılacak kontrolüdür.",
  "Kat Göstergesi ( Kabinin hangi katta olduğunu belirtir.)",
  "(Varsa) Aşağı / Yukarı Yön Butonu ( Yalnızca gitmek istediğiniz yöne basınız.)",
  "Meşgul Butonu (Bu buton yanıyorsa asansörün meşgul olduğunu gösterir.)",
  "Kabin Katta Butonu (Bu buton yanıyorsa asansör kabinin o katta olduğunu gösterir.)",
  "Servis Dışı Butonu ( Bu buton yanıyor ise asansörün kullanılamayacağını belirtir.)",
  "(Varsa) Çağır Butonu ( Asansörü bulunduğunuz kata çağırmak için kullanılır.)",
  "1- Kabinin hangi katta olduğunu kat göstergesinden takip edebilirsiniz.",
  "2- Hangi kat ve doğrultuya gitmek istediğinizi belirledikten sonra, “varsa” aşağı/yukarı yön butonuna veya",
  "çağırma butonuna “ Ç “ basınız.",
  "3- Kabinden çıkmak isteyenlerin geçiş yolu üzerinde durmayınız, geçişe engel olmayacak bir yerde bekleyiniz.",
  "4- Asansör yarım otomatik ise kapı kolundan tutarak kapıyı çekiniz. Kabin içinde yolcu varsa kapıyı açmaya çalışacağını unutmayıp kapının size çarpmayacağı bir yerde bekleyiniz. Asansör tam otomatik bir asansör ise bekleyiniz kapı otomatik olarak açılacaktır.",
  "5- Asansör beklediğiniz kata geldiğinde, asansörün dolu olması halinde mutlaka kabine girmeye çalışmayınız, asansörün tekrar bulunduğunuz kata gelmesini bekleyiniz, (varsa) diğer asansörü kullanınız.",
  "6- Otomatik kapılı asansörlerde, kapısı kapanmakta olan asansörün kapısını açmaya çalışmayınız, asansörün tekrar bulunduğunuz kata gelmesini bekleyiniz, (varsa) diğer asansörü kullanınız.",
  "Kabin İçi Display ( Asansörün seyir halinde hangi kata olduğunu ve gittiği yönü gösterir.)",
  "Kat Butonları ( Gidilmek istenen katın butonuna basınız.)",
  "Aşırı Yük İkaz Lambası ( Asansörün taşıma kapasitesinin aşılması durumunda yanar. Asansör hareket etmez.)",
  "Kapı Kapama Butonu ( Kabin kapısının kapanmasını sağlar.)",
  "Kapı Açma Butonu ( Kabin kapısının açılmasını sağlar.)",
  "Acil Aydınlatma Lambası ( Elektrik kesilmesi gibi acil durumlarda kabinin aydınlatılmasını “5 lux” sağlar.)",
  "Diafon Butonu ( Acil durumlarda kabin dışı ile irtibat sağlanması için kullanılır.)",
  "İmdat Butonu ( Acil durumlarda basılarak sesli ikaz verilebilir.)",
  "Fan Butonu ( Suni havalandırma yapılan asansörlerde, kabinin havalandırılması içi kullanılır.)",
  "Kabin ve Kat Etiketleri",
  "Kat etiketi olup hangi katta bulunduğunuzu gösterir.",
  "Asansöre bakım yapıldığında bu etiket kullanılır. Bu etiketi görüldüğünde asansör kullanılamaz.",
  "Makine dairesini gösterir. Yetkili olmayanların girmesi tehlikeli ve yasaktır.",
  "Asansörlerde asansörün taşıyabileceği maksimum kişi veya kapasiteyi belirtir.",
  "Kullanılan halatın teknik özelliklerini ve işletmeye konulduğu tarihi yazar.",
  "Asansörünüzün, Avrupa Birliği Normlarına uygun olarak imal edildiğini gösterir. Bu etiketin kabin içinde bulunması zorunludur.",
  "Asansörü imal eden firma bilgilerini, yapım yılını, hızını ve asansörün seri no.sunu gösterir etikettir.",
  "5 ASANSÖR SAHİBİNİN SORUMLULUKLARI",
  "* Bina sorumlusu, asansörün güvenli bir şekilde çalışmasını sağlamak üzere bakımını yaptırmaktan ve bakım ücretinin ödenmesinden sorumludur.",
  "* Bina sorumlusu, engellilerin erişilebilirliği için asansörün güvenli bir şekilde sürekli olarak çalıştırılmasını sağlar. Kamuya açık alanlarla ilgili olarak birinci cümlede belirtilen konuya ilişkin şikâyetler ilgisi nedeniyle Valilik bünyesinde bulunan erişilebilirlik izleme ve denetleme komisyonuna, konutlarla/meskenlerle ilgili şikâyetler ise konutun/meskenin bağlı bulunduğu ilgili idaresine iletilir.",
  "* Bina sorumlusu, asansörle ilgili herhangi bir tehlikeli durumu bakım sözleşmesi imzalanan asansör monte eden veya onun yetkili servisine iletir ve söz konusu asansöre, asansör monte eden veya onun yetkili servisi tarafından müdahale edilene kadar gerekli güvenlik tedbirini alır.",
  "6 KULLANMA TALİMATLARI",
  "• Makine dairesinin kapısının kilitli tutulması; Asansör makine dairesinde bulunan makine ve elektrik aksamlarını dışarıdan gelebilecek doğal etkenlere karşı korumak amacıyla, makine dairesi kapısı sürekli kilitli tutulacaktır. Makine dairesi kilit anahtarı bina yönetimini haricinde kimsede bulundurulmayacak ve asansör bakımını yapan firma çalışanları veya yetkilileri haricinde kimseye verilmeyecektir.",
  "• Makine Dairesi Kullanımı; Makine veya makara dairelerinde asansör makineleri haricinde asansör makine ve makaraların çalışmasını engelleyecek şekilde, hiçbir eşya, cihaz, alet v.s bulundurulmayacaktır. Bakımcı Firma tarafından ya da yapılan bakım anlaşmasına göre yönetim tarafından, makine dairelerinde her zaman bakım malzemesi (yağ, üstübü, mazot, gres yağ vs.) makine dairesinde uygun yerlerde bulundurulacaktır.",
  "• Güvenli yükleme ve boşaltma; Belirtilen beyan yükünden fazla yükleme yapılmayacaktır. Asansör kabini görmeden kabine girilmemelidir. Asansöre girerken ve çıkarken kapılar iyice kapatılacaktır. Asansör kat seviyesinde durmadan önce kapıları açıp çıkmayınız.",
  "• Asansör kuyusu tamamen kapalı durumdadır.",
  "• Yetkili kişilerin müdahalesini gerektiren olaylar; Asansörün arıza yapması durumunda arıza, en kısa zamanda bakımcı firmaya bildirilmelidir.",
  "• Asansörün Kullanımı;",
  "1- Asansöre binmeden önce kabinin katta olduğundan emin olunuz.",
  "2- Asansöre binip, inerken dikkatli olunuz. Asansör ve kat seviyesi farklılıkları olabilir, takılıp düşebilirsiniz.",
  "3- Kabin kasetindeki aşırı yük ikaz lambasının yanmadığından emin olun; eğer yanıyorsa asansörden hızlı hareketlerle ininiz.",
  "4- Gideceğiniz kata karar verip; şekilde gösterilen kabin kasetinde uygun kat düğmesine basınız.",
  "5- Asansörün geldiği kata, kabin içi kat göstergesinden bakarak, gitmek istediğiniz kat olduğunu doğruladıktan sonra ininiz.",
  "6- Çocukları, evcil hayvanları (kedi köpek vs.) kontrol altında tutunuz.",
  "7- Otomatik kapılı asansörlerde, kapının açılması bir açma butonu aracılığıyla oluyorsa, kapıyı butonuna basarak açınız. Kabin katta durmadan kapıyı açmaya çalışmayınız.",
  "8- Kabine girerken ve kabinden çıkarken oyalayıcı hareketlerden kaçınınız.",
  "9- Kabinde tutamak (küpeşte) varsa tutunuz.",
  "10- Kat göstergelerine dikkat ediniz ve izleyiniz.",
  "11- Asansörün durmasına karşın, otomatik kabin kapılı asansörlerde kapı açma butonu ile de kapı açılamıyorsa veya asansör kat arasında kalırsa kesinlikle paniğe kapılmayınız.",
  "12- Böyle bir durumda imdat butonu ve / veya diafon butonunu kullanarak dışarıdaki kişilerle irtibata geçiniz.",
  "13- Elektrik kesilmesi sonucu kabin içinde kalınırsa yine imdat ve diafon butonunu kullanabilirsiniz. (İmdat ve diafon beslemesi şebeke geriliminden ayrı bir kaynaktandır.)",
  "14- Yukarıda belirtilen durumlar dışında gereksiz yere seyir halindeyken stop ve imdat butonuna basmayınız ve çocukların basmamasını sağlayınız.",
  "15- Asansör seyir halindeyken kabin kapısını açmaya çalışmayınız.",
  "1- Asansör içinde iki kat arasında kalan kişilerin kurtarılmasında kapı kilit anahtarının kullanılması tehlikeli olduğundan, kurtarma işlemi makine-motor grubu üzerindeki el freni yardımıyla yapılmalıdır.",
  "2- Makine dairesi kapısı veya giriş kapağı güvenlik nedeniyle sürekli kilitli tutulmalı, ancak her hangi bir nedenle içeri girilmesi gerektiğinde anahtar bina yöneticisi ve görevlisi ile belirlenecek kişilerde bulunmalıdır.",
  "3- Kuyu boşluğuna kâğıt ve benzeri yanıcı maddelerin atılması önlenmeli, buradan başlayacak bir yangın kısa sürede kabini etkileyeceği göz önünde bulundurulmalıdır.",
  "4- Kabin girişine konulan fotosel ya da eşik kontağı gibi güvenlik tertibatları ( Kapı sıkışmalarını engellemek için) mutlaka çalışır durumda tutulmalı, özellikle çocukların bunlarla oynamaları, bozmaları önlenmeli ve uyarılmalıdır.",
  "5- Kat kapı camları telli dahi olsa el ve parmak girecek kadar açıklık olduğunda cam değiştirilinceye kadar güvenlik nedeniyle asansör işletmeye kapatılmalıdır.",
  "6- Makine dairesi depo olarak kullanılmamalıdır. Asansör ile ilgili teçhizatlar haricinde makine dairesinde başka teçhizatlar bulundurulmamalıdır. ( uydu anteni ekipmanları vb.)",
  "7- Makine dairesinde bulunan havalandırma pencereleri ile varsa kapılar uygun bir havalandırma sağlanması için panjurlu hale getirilmelidir.",
  "8- Makine dairesindeki aydınlatma tesisatı çalışır durumda bulundurulmalıdır.",
  "9- Makine dairesine kolayca görülebilecek bir yere kurtarma talimatı asılmalıdır. Kabin içinde bulunan imdat butonu özellikle elektrik kesilmeleri ve arıza durumunda kullanılması gerektiğinden acil aydınlatma kaynağından beslenmesi sağlanmalıdır.",
  "10- Asansör kabinin katta olduğunu anlamak için kabin içinde mutlaka sürekli aydınlatma sağlanmalıdır.",
  "11- Kabin içi güvenlik kapısı kılavuzları içinde pislik birikmesi engellenmelidir.",
  "12- Merdiven temizliği yapılırken kuyu dibine su girmesi önlenmelidir.",
  "13- Tehlike anında İMDAT butonlarına basılmalı, her iki butonun gereksiz kullanılmaları önlenmelidir.",
  "14- Bir yangın, deprem vs. gibi doğal afet anında kaçış için asansör kullanılmamalıdır.",
  "15- Asansöre 12 yaşından küçük çocukların yalnız başına binmeleri yasaktır.",
  "8 KULLANIM HATALARI İÇİN BİLGİ",
  "1- Asansör için tasarlanan insan sayısından fazla kişi asansöre binmemelidir.",
  "2- İnsan taşımak için tasarlanmış asansörlerde yük veya eşya taşınmamalıdır.",
  "3- Kremayer iç kapılı asansörlerde kabin içinde girişe yakın durulmamasına dikkat edilmelidir.",
  "4- Kat butonu üzerindeki yön butonlarından sadece gideceğiniz yöndeki (yukarı veya aşağı ) butona basılmalıdır.",
  "5- Meşgul lambası yanıyorken çağırma butonuna basılmamalıdır.",
  "6- Emniyet açısından asansöre girip çıkarken oyalanılmamalıdır.",
  "9 YETKİLİ KİŞİLERİN MÜDAHALESİNİ GEREKTİREN DURUMLAR",
  "Aşağıda belirtilen durumlar ile karşılaşılması halinde, mutlaka sözleşmeli olduğunuz bakım servisi veya bina sorumlusu ile irtibata geçiniz. Kendi başınıza müdahale etmeyiniz. 1- Asansörün kat arasında arızalanması. 2- Asansörün hareket etmemesi. 3- Asansör motorunun çalışmaması. 4- Arızalanan asansörde mahsur kalan kişilerin kurtarılma ihtiyacı. 5- Her hangi bir imdat çağrısı yapılması. 6- Elektrik kesintisi sonucu arıza. 7- “Kapı Kilit Açma Anahtarı”nın kullanılması gereken durumlar.",
  "1- Asansör, elektrik kesintisi veya arıza gibi nedenlerden kabini iki kat arasında kalabilir. Asansörünüz tasarım ve montaj aşamasında bu tür riskli durumlar düşünülerek her türlü önlem alınmıştır.",
  "2- Periyodik bakımları düzenli ve bilinçli yapılan asansörümüzde bu durumlar hayati risk içermez. Kurtarma gibi önemli ve riskli olabilecek durumlarda “asansör firması” çağırılmalıdır.",
  "3- Kurtarma konusunda eğitim almış kişiler var ise kılavuzda ve makine dairesinde belirtilen kurtarma talimatına aynen uyulmalıdır. Bu talimatlarda kurtarma adım adım anlatılmıştır.",
  "4- Eğitim almış kişiler tarafından yapılan kurtarma işleminde belirtilen adımların dışında anormal bir durum gözlenir ise bu işleme devam edilmemeli ve mutlaka “Asansör Firması”na bildirilmeli ve daha profesyonel bir yardım alınmalıdır.",
  "5- Acil Durumda Makine Dairesinin Kullanımı Kabinde mahsur kalan kişilerin kurtarılması; (Şekil 1) Asansörün elektriğini ana elektrik panosunun üzerindeki ana şalteri \"0\" konumuna getirin. Makine dairesinde bulunan kurtarma talimatını inceleyin ve buna göre hareket edin. Talimatın anlatımına destek olarak aşağıdaki maddeleri uygulayın.",
  "ACİL DURUM KİLİT AÇMA ANAHTARININ KULLANIMI",
  "Tanım: Asansörün Kat Arasında kaldığı durumlarda, içerisindeki şahısları kurtarmak amaçlı yapılmış, kapı kilit sistemini açtırarak, kapının açılmasını sağlayan anahtardır a. Anahtarı Kullanmadan önce şebeke elektriği kapalı olsa dahi, asansörün elektriğini ana şalterden tamamen kapatın ve asansörün elektriğinin kapalı olduğundan emin olun. b. Kilit açma anahtarını kapı kasası üzerinde bulunan yuvarlak delik üzerine yerleştirin. c. Kapının durumuna göre anahtarı sağ veya sol yönünde çevirin ve elinizi sabit tutun. d. Diğer elinizi kapı tutamağından tutarak kapıyı açın. e. Tam Otomatik Kapılı Asansör Kapılarında ise, açma anahtarını açık konumda sabit tutmak koşulu ile otomatik kapıyı, kapı açıklığından tutarak kapı açılma yönüne doğru çekin. f. Kapıyı açtıktan sonra kabin içerisindeki şahsın güvenli bir şekilde dışarı çıkmasına özen gösterin ve şahıs dışarı çıkarken kapının kapanmaması için dikkatli bir şekilde kapıyı tutun. g. Kabin içindeki şahıslar çıktıktan sonra,kapının tamamen kapanmış ve kilitlenmiş olduğunu kontrol edin."
];

export const BAKIM_KLAVUZU: string[] = [
  "1- Bina yönetimi, asansörün bakımını garanti kapsamı dahilinde ilk iki yıl montajı gerçekleştiren asansör firmasına, ondan sonraki yıllarda TSE Hizmet Yeterlilik Belgesine sahip olan asansör bakım firmalarına yaptırmalıdır. 2- Garanti süresi içinde bina yönetimi ile asansörün motajcısı veya onun yetkili servisi arasında aylık bakım sözleşmesi yapılması zorunludur. 3-Garanti süresi bitiminde bina yönetimi başka bir bakım firması ile çalışırsa montaj firması bakım talimatına uyulmalıdır. Aksi halde yanlış veya hatalı bakım sonucu oluşacak durumlardan montaj firması sorumlu değildir. 4- Bakımlar özel durum olmadığı takdirde bakım talimatında belirtilen şekilde yapılmalıdır. 5- Güvenlik ekipmanlarının bakım ve ayarları kullanma kılavuzlarına göre yapılmalıdır. 6- Bakıma başlanılmadan önce gerekli emniyet tedbirleri alınmalıdır. 7- Bütün kat kapılarına “Asansöre Bakım Yapılıyor” levhası asılmalıdır. 8- Makine ve elektrik aksamına ait bakım yapılırken ana şalter kapatılarak elektrik kesilmelidir. 9- Yapılan bakım asansör bakım defterine işlenmelidir. 10- Bakım esnasında bulunan uygunsuzluklar yazılı olarak bina yönetimine bildirilmelidir. Bakım yapan firmanın yazılı ihtarına rağmen uygunsuzluk giderilmediği taktirde sorumluluk bina yönetimine aittir. 11- İki kişiden az olmamak üzere binada bulunan kişilere acil durum kurtarma çalışması konusunda eğitim verilmelidir. Acil durum kilit açma anahtarı ( üçgeni ) tutanak ile eğitim alan kişilere teslim edilmelidir.",
  "Elektrikli Asansörlerin periyodik bakımlarının TS EN 13015 + A1 e uygun olarak yapılmasını sağlamak, arıza oranlarını azaltmak ve müşteri memnuniyetini sağlamak.",
  "2.1. Bakıma başlamadan önce emniyet tedbiri olarak, kat kapılarına “ASANSÖR BAKIMDA” levhası asılacak.",
  "2.2. Kumanda panosu, makine ve motorun bakımlarına başlamadan önce, termik şalterden elektrik kesilecek.",
  "2.3. Genel olarak bütün asansör parçalarının temizliğini, toz ve korozyon bulunup bulunmadığı kontrol edilecek.",
  "2.4. KUYU ALT BOŞLUĞU: * Kılavuz rayların altında yağ / gres yağı birikmiş mi kontrol edilir. * Kuyu alt boşluğunun temiz, kuru olduğunu ve inşaat vb. atıkların bulunmaması kontrol edilir.",
  "2.5. SIÇRAMAYA KARŞI TERTİBAT (varsa): * Serbest hareket ve çalışma kontrol edilir. * Halatlar eşit gerginlik bakımından kontrol edilir. * Anahtar, takıldığı yerde kontrol edilir. * Yağlama kontrol edilir.",
  "2.6. HİDROLİK TAMPONLAR (varsa): * Yağ seviyesi kontrol edilir. * Yağlama kontrol edilir. * Anahtar takıldığı yerde kontrol edilir. * Bağlantılar kontrol edilir.",
  "2.7. TAHRİK MOTORU: * Rulmanlar aşınma bakımından kontrol edilir. * Yağlama kontrol edilir. * Komütatörün durumu kontrol edilir. * Dişli kutusu; Dişli aşınma bakımından kontrol edilir. Yağlama kontrol edilir. * Tahrik Kasnağı; Durum ve aşınma bakımından yivler kontrol edilir. Muhafaza kontrol edilir. * Frenler; Fren sistemi kontrol edilir. Aşınma bakımından bölümler kontrol edilir. Katta durma hassasiyeti kontrol edilir. * Motor hareket süresi sınırlayıcısı; Çalışma kontrol edilir.",
  "2.8. KUMANDA PANOSU: * Muhafaza temizliği, kuru olması ve toz bulunmaması bakımından kontrol edilir.",
  "2.9. HIZ REGÜLÂTÖRÜ ve GERME MAKARASI: * Hareketli bölümler rahat hareket ve aşınma bakımından kontrol edilir. * Çalışma kontrol edilir. * Anahtar kontrol edilir.",
  "2. 10. SAPTIRMA KASNAĞI ve MAKARALAR: * Durum ve aşınma bakımından yivler kontrol edilir. * Normal olmayan ses ve / veya titreşimler için rulmanlar kontrol edilir. * Muhafaza kontrol edilir. * Yağlama kontrol edilir.",
  "2.11. KABİN ve KARŞI AĞIRLIK RAYLARI: * Gerekli yerlerde bütün kılavuz yüzeyleri, üzerlerindeki yağ tabakası bakımından kontrol edilir. * Bağlantılar kontrol edilir. * Patenler; Kılavuz patenleri aşınma bakımından kontrol edilir. Bağlantılar kontrol edilir. Gerekli olan yerde yağlama kontrol edilir.",
  "2.12. ELEKTRİK TESİSATI: * Yalıtım kontrol edilir.",
  "2.13. KABİN: * Acil durum aydınlatması, asansör kabini düğmeleri, anahtarlar kontrol edilir. * Acil alarm tertibatı; Çalışma kontrol edilir. * Panellerin ve tavanın bağlantıları kontrol edilir.",
  "2.14. PARAŞÜT FRENLER: * Hareket eden bölümler serbest hareket olması ve aşınma bakımından kontrol edilir. * Yağlama kontrol edilir. * Bağlantılar kontrol edilir. * Çalışma kontrol edilir. * Anahtar kontrol edilir.",
  "2.15. ASKI HALATLARI: * Aşınma, uzama ve gerginlik bakımından kontrol yapılır. * Sadece gerekli yerde yağlama kontrol edilir. * Halat Şişeleri; Yıpranma ve aşınma için kontrol edilir. Bağlantılar kontrol edilir.",
  "2.16. DURAK KAPILARI: * Durak kilitlerinin çalışması kontrol edilir. * Rahat çalışma bakımından kapılar kontrol edilir. * Kapı kılavuzlanması kontrol edilir. * Kapı aralıkları kontrol edilir. * Tel halat, zincir veya kayış kullanıldığında, bunların uygunluğu kontrol edilir. * Acil kilit açma tertibatı kontrol edilir. * Yağlama kontrol edilir.",
  "2.17. KABİN KAPISI: * Kapı kapanma kontağı veya kilidi kontrol edilir. * Rahat hareket bakımından kapılar kontrol edilir. * Kapı kılavuzlanması kontrol edilir. * Kapı aralıkları kontrol edilir. * Tel halat, zincir veya kayış kullanıldığında, bunların uygunluğu kontrol edilir. * Yolcu kapısı koruma tertibatı kontrol edilir. * Yağlama kontrol edilir.",
  "2.18. KAT SEVİYELERİ: * Duraktaki duruş hassasiyeti kontrol edilir.",
  "2.19. SINIR GÜVENLİK KESİCİLER: * Çalışma kontrol edilir.",
  "2.20. ELEKTRİK GÜVENLİK TERTİBATI: * Çalışma kontrol edilir. * Elektrik güvenlik zinciri kontrol edilir. * Doğru sigortaların takıldığı kontrol edilir.",
  "2.21. DURAK KUMANDALARI ve GÖSTERGELER: * Çalışma kontrol edilir.",
  "2.22. KUYU AYDINLATMALARI: * Çalışma kontrol edilir."
];

export const SON_KONTROL: string[] = [
  "Projeye uygun tesis edilmesi Aynı kuyu içinde 3’den fazla asansör kabini düzenlenemez.",
  " Tam Kapalı Asansör Kuyusu  Kısmen Kapalı Asansör Kuyusu",
  "Muayene Kapısı / kapağı ölçülerinin standarda uygunluğu (elle kilitlenebilir bir tertibata sahip olduğunu ve elektrik güvenlik tertibatıyla denetlendiği)",
  "Muayene Kapısı/ Kapağı: h: …....…… cm, g:…............cm h > 2,5 m ise giriş kapısı gerekir.",
  "BYKHY Madde 62 - Asansör kuyusunda en az 0.1 m2 olmak üzere kuyu alanının 0.025 katı kadar bir havalandırma ve dumandan arındırma bacası bulundurulur veya kuyular basınçlandırılır.",
  "Asansör kuyusu yangına en az 60 dakika dayanıklı ve yanıcı olmayan malzemeden yapılır.",
  "Art arda gelen durak kapısı eşikleri arasındaki mesafenin 11 m’yi aştığı durumlarda, aşağıdaki şartlardan biri yerine getirilmeli ve bu kısımlarda aşağıdakiler bulunmalıdır: a) Ara acil durum kapıları veya b) 5.4.6.2’de belirtilen hüküm uyarınca, her biri acil durum kapılarıyla donatılmış komşu kabinler. NOT \"Art arda\" ifadesi, öne veya yana açılma konfigürasyonlarına bakılmaksızın, durak kapıları olan iki komşu kat anlamına gelir.",
  " 1,80 m asgari yükseklik ve 0,50 m asgari genişlik  Kuyu içine doğru açılmamalı  Kapı ve kapaklar için anahtarla çalışan bir kilit sağlanmalı, bu anahtar olmadan kapı tekrar kapatılabilmeli ve tekrar kilitlenebilmeli.  Kuyu içinden kilitli olsalar dahi anahtarsız açılabilmeli  Kapatılmış konumu kontrol eden, 5.11.2’ye uygun bir emniyet kontağı ile donatılmalı",
  "Asansör kuyusu altındaki hacim",
  "Karşı ağırlıkta fren tertibatı ve hız regülatörü takılmalıdır.",
  "Seperatör (Kabin-Karşı ağırlık arası) h= 2,0 m",
  "En fazla 30 cm’den başlamalı. Yerden yüksekliği:…..........cm",
  "Bölme duvarı, yuvarlak veya kare kesitli 5 cm2lik bir alana eşit olarak dağıtılmış 300 N'luk bir kuvvet, herhangi bir noktasına dik açıda uygulandığında, sapma göstererek karşı ağırlıkla veya dengeleme ağırlığıyla çarpışmamasını sağlayacak yeterli rijitliğe sahip olmalıdır.",
  "h…................cm < 2,50 m, X < 50 cm ise kuyu boyunca",
  "Merdiven (h =< 2,5 m ise merdiven yapılmalı) ● Genişlik min. 280 mm, basamaklar arası dikey mesafe 250-300 mm eşit aralıkta olmalı, ● Basamak kesit alanı min. 25 mm, maks. 35 mm, tutamak gen. maks. 35 mm, der. maks. 100 mm, ● Dikey ise duvar ile merdiven arası min. 200 mm olmalı, ● Taşınabilirse ağırlık maks. 15 kg olmalı, basamakların yeterli dayanımı min. 1500 N olmalı,",
  "● Merdiven tutamaklarının durak zemin seviyesinden en az 1,10 m yükseklikte olmalı, ● Korozyona karşı tedbir alınmalı, alüminyum veya çelikten yapılmış olmalı, ● Kuyudan çıkarılması mümkün olmamalı, Dayandığı yerde sabitlenmiş olmalı ve kayması önlenmeli, ● Saklandığı yerde duraktan mesafesi maks. 800 mm, ● Açıkken basamak ortasından durak eşiğine yatay mesafe maks. 600 mm olmalı, birinci basamak ile )",
  "Kuyuya giriş kapısı yok ise, kapı kilidine erişim",
  "Kuyu alt boşluğu merdiveninden 1,80 m yükseklikte ve azami 0,80 m yatay mesafeyi aşamamalı, yok ise kalıcı tertibat takılmalı",
  " Durdurma butonu ve işaretlemesi  Alarm tertibatı ve işaretlemesi (Haberleşme)  Kumanda tertibatı çalışması ve işaretlemeleri  By-pass tertibatının uygunluğu (sesli ve ışıklı ikaz)  Sıfırlama (Reset) anahtarı",
  "Kuyu Derinliği =…...................cm",
  "Derinlik =< 1,60 m ise 1 adet dur butonu (asgari 40 cm yükseklikte, azami 75 cm derinlikte) Derinlik > 1,60 m ise 2 adet dur butonu (1. Dur butonu asgari 100 cm yükseklikte, azami 75 cm derinlikte) (2. Dur butonu kuyu zemininden 120 cm yükseklikte, azami 75 cm derinlikte) Birden fazla kontrol kumanda istasyonu, ”KONTROL”e geçmiş ise, kontrol kumanda istasyonunda aynı basma butonları aynı anda basılmadıkça, bunların herhangi birinden kabini hareket ettirmek mümkün olmamalıdır.",
  "Kuyu aydınlatma anahtarı ve işaretlemesi",
  "…......Lüks (X> 50 lüks, diğer X > 20 lüks) (Anahtar 100 cm yükseklikte)",
  "Regülatör gergi makarası ağırlığı/yayı, mekanik ve emniyet kontak bağlantıları ve kasnak korumanın uygunluğu (Kabin ve karşı ağırlık için ayrı ayrı kontrol edilir.)",
  "Kılavuz ray bağlantısı (konsol, flanş) projeye ve standardın şartlarına uygunluğu (Kabin, K. Ağırlık / D. Ağırlığı)",
  "Kabin konsol arası mesafe (l) :……......cm (En uzun mesafe ölçülmelidir) K. / D. Ağırlık konsol arası mesafe (l) :…..............cm (En uzun mesafe ölçülmelidir)",
  "Elektrikli ise, Kabin tam kapanmış tampon üzerinde otururken, dört şart yerine getirilmeli (M = Y + X + S = ………. + ………. + ……. = ) M: Düşülecek mesafe, Y: Eşik arası mesafe, X: Kayma Payı, S: Strok Mesafesini ifade eder.",
  "(i) (G. H. >  0,40*0,50*2,00 m /  0,50*0,70*1,00 m /  0,70*1,00*0,50 m) (ii) ...............m (Kabin altı – kuyu zemini arası > 0,50 m) (- M çıkarılacaktır) (iii)...............m (Kabin etek sacı – kuyu zemini arası ve kabin patenleri, karkası – kabin kılavuz rayı arası 0,15 m yatayda 0,10 m) (- M çıkarılacaktır) (iv)...............m (kabin altı ile denge halatı gergi ter. arası > 0,30 m) (- M çıkarılacaktır)",
  "Kabin güvenlik tertibatı ve emniyet kontağı uygunluğu",
  "Kapasite (P+Q):….......................(kg)",
  "K. / D. Ağırlığı güvenlik tertibatı ve emniyet kontağı uygunluğu",
  "Hidrolik ise, Kabin tam kapanmış tampon üzerinde otururken, altı şart yerine getirilmeli (M = Y + X + S = ……. + ……. + ……. = ....... ) M: Düşülecek mesafe, Y: Eşik arası mesafe, X: Kayma Payı, S: Strok Mesafesini ifade eder.",
  "(i) (G. H. < 0,40*0,50*2,00 m / 0,50*0,70*1,00 m / 0,70*1,00*0,50 m) (ii)...............m (Kabin altı – kuyu zemini > 0,5 m (- M çıkarılacaktır)) (iii).............(Kabin etek sacı – kuyu zemini ve kabin patenleri, karkası – kabin kılavuz rayı > 0,15 m) ) (- M çıkarılacaktır) (iv) ………… m (kabin altı - piston mesnetleri, borular, bağlantı parçaları > 0,5 m (seperatör ile mesafe 0,10 m düşürülebilir) ) (- M çıkarılacaktır)",
  "(v)…........m (piston başı - kuyu tabanına monte edilmiş teçhizat > 0,5 m) ) (- M çıkarılacaktır) (vi)…........m (Dengeleme ağırlığı ray-paten > 0,1 m) ) (- M çıkarılacaktır)",
  "Kabin/piston (Silindir) bağlantı uygunluğu",
  "Kabin ve (varsa) dengeleme ağırlıklarının halat bağlantılarının uygunluğu",
  "Halat soketleri, Halat klemensleri, Gevşeme tehlikesine karşı emniyet kontağı",
  "Kabin ve K. ağırlık/D. Ağırlığı tamponunun uygunluğu",
  "K. Ağırlık / D. Ağırlığı Tamponu",
  "Adet:…............. Strok:….............cm",
  "Halat ağırlığının halatlarla dengelenmesinin uygunluğu",
  "V < 3,0 m/s ise halat veya zincir, V> 3,0 m/s ise halat, V > 3,5 m/s ise gergi kasnağı ve emniyet kontağı",
  "Kabin altı kasnakların montaj ve kasnak halat atma pimi",
  "Halat Çapı / Kasnak Çapı (x > 1/40)",
  "h:…..............cm (h > 75 cm, 60o ve 20 mm’den az olmamalı)",
  "Kuyu işaretlemeleri, temizliği",
  " Kabin alt paten montajının uygunluğu",
  " Kabin altı bükülgen kablo (fleksible) takozu montajı uygunluğu",
  " Kabin kapılarının yüzeylerinin deliksiz olduğunu,  Kabin girişini tam olarak kapandığını, Kapı açıklıklarının 6 mm’yi geçmemelidir.",
  "Menteşeli kabin kapılarında, durdurma mesnetlerinin bulunması",
  "Kabinin yüklenme ve boşaltılması için yeterli dayanım",
  "Kabin kapı kılavuzlarının uygunluğu ve yeterli dayanımı",
  "Düşey hareket eden sürmeli kabin kapılarının panellerinin bağımsız iki askı elemanına tespit edilmesi",
  "Halat ortasından-ortasına ölçülen makara çapı, halat çapı oranının en az 25 katı ve halat güvenlik katsayısı en az 8 olduğunu teyit ediniz. Askı halatları veya zincirlerinin, kasnak oluklarından veya dişlilerden çıkması engellendiğini teyit ediniz.",
  "Kabin giriş eşik uygunluğu (x ≤ 35 mm) Tüm katlarda ölçülecektir.",
  "Eşik mesafesi:…...........mm (en geniş ölçü kaydedilir)",
  " İşletme Talimatı,  Üretici Bilgi Plakası Seri No  Kapasitesi (kişi - kg)  İmal Yılı",
  "Yük Asansörlerinde her zaman yükleme alanında görülebilen bir işaret beyan yükünü göstermelidir.",
  "Kabin alanının projeye ve standarda uygunluğu",
  "Sesli ve ışıklı ikaz olmalıdır.",
  "Cam duvar olması halinde bağımsız korkuluk takılmalı (lamine cam lamine ve korkuluk boyu 900-1100 mm arasında olmalı)",
  "Kabin alev almaz olması EN 13501-1:2007+A1:2009'un gerekliliklerini karşılamalıdır: Zemin kaplaması: Cfl-s2; Duvar: C-s2, d1; Tavan: C-s2, d0. (A1 > A2 > B > C > D > E > F, s1 > s2, d0 > d1> d2))",
  "Duman oluşumu için ilâve sınıflandırmalar: s3 Duman oluşumu açısından herhangi sınırlama yok / s2 Duman oluşumunun artış hızının yanısıra toplan duman oluşumu sınırlandırılmıştır. / s1 s2’den daha ağır kriterler sağlanmalıdır. Yanma damlaları/tanecikleri için ilâve sınıflandırmalar: d2 Sınırlama yok / d1 Belirlenen bir süreden daha uzun süreli yanma damlaları/tanecikleri olmamalı / d0 Yanma damlaları/tanecikleri oluşmamalı",
  "Kabinin alt ve üst kısımlarında havalandırma menfezleri",
  "Kabinin üst kısmında yer alan havalandırma açıklıklarının etkili alanı, kullanılabilir kabin alanının en az %1'i olmalıdır ve aynı durum kabinin alt kısmındaki açıklıklar için de geçerlidir.",
  " Kabin aydınlatmasının uygunluğu (100 lüks)  Acil durum aydınlatması (5 lüks – 1 saat)  Alarm / Haberleşme (senaryo kontrolü)",
  "Işık Şiddeti: ……………… / ……… lüks (Normal – Acil aydınlatma) Zeminden 1m yukarıda ölçülmelidir. En az paralel bağlı 2 adet lamba olmalıdır. Alarm cihazı kabin merkezinden zeminden 1 m yukarıda ölçülür.",
  "Kapının kapanmasını engelleme kuvveti F: …….......N (x<150 N)",
  "Kabin kapısının kinetik enerjisi E:…..........J (x <10 J)",
  "5 cm2 300 N uygulandığında 1 mm kalıcı şekil değişikliği, 15 mm elastik şekil değiştirme 100 cm2 1000 N uygulandığında kalıcı şekil değiştirmenin olmamalıdır. Cam Panel olması halinde TS EN 81-20 Madde 5.3.5.3.4. şartları aranır.",
  "Sıkışma kontağı ve ışın perdesinin (boy fotoseli) çalışması",
  " 25 mm – 1600 mm arası yerleşim uygunluğu Koruyucu tertibatın devre dışı bırakılması veya arıza durumunda, asansör çalışmaya devam ediyorsa, kapıların kinetik enerjisi 4 J’ e sınırlandırılmalı ve akustik sinyal, kapı (kapıların) herhangi bir zamandaki kapanmasında çalışmalıdır.",
  "Kabin kapısının panel kapanma hızı V:…..........m/s",
  "Makina Gücü İle Çalışan, Otomatik Olmayan Kapılar için V < 0,3 m/s",
  "Düşey hareket eden sürmeli kabin kapısının uygunluğu",
  "Bu tip kapılar sadece yük asansörlerinde kullanılır.",
  "Kabin kapısı kilitleme tertibatı uygunluğu",
  "Kabin buton ve gösterge montaj ve çalışması Kapı aç butonunun bulunduğunu ve çalıştığı",
  "a) Kumanda butonları için: -2, -1, 0, 1, 2, 3 vb. sembollerle; b) İmdat butonu: sarı renkli çan ( ) biçiminde sembolle, c) Kapıyı tekrar açma: ( ) sembolü ile, d) Kapıyı kapatma düğmesi: ( ) sembolü ile, (TS EN 81-70 Madde 5.3.2.)",
  "Kabin kapısının kapalı olduğunun elektriksel denetimi",
  "Kabin kapısının kabin içindeki insanlar tarafından açılmasını kısıtlamak için aşağıdaki şekilde bir araç sağlanmalıdır: a) Kabin hareket ederken kabin kapısının açılması 50 N'dan fazla bir kuvvet gerektirmelidir ve b) Kabin, 5.3.8.1'de tanımlanan bölgenin dışındayken, kabin kapısını sınırlama mekanizmasında 1000 N bir kuvvet ile 50 mm'den daha fazla açmak mümkün olmamalı ve aynı zamanda kapı otomatik güç çalışmasıyla açılmamalıdır.",
  "Çok panelli, panelleri mekanik olarak bağlantılı sürmeli kabin kapılarının kapalı olduğunun denetlenmesi",
  "Kabindeki şahısların kabin dururken ve varsa kabin kapısı tahrik mekanizmasının elektrik bağlantısı kesilmişken kabini terk edebilmesi",
  "Kabin kapısının, en azından kilit açılma bölgesi içinde açılabildiğini teyit ediniz. Kilidin açık olduğu bölgede (Madde 5.3.8.1) herhangi bir nedenden dolayı asansör durursa, 300 N’dan daha büyük olmayan bir kuvvet ile aşağıdaki konumlarda el ile kabin ve durak kapısını açmak mümkün olmalıdır: a) Durak kapısı, acil durum kilit açma anahtarı veya kabin kapısı yardımıyla kilit açılmış olması ile kilidin açılmış olmasından sonra duraktan, b) Kabin içinden.",
  "İmdat kapağı/kapısı varsa, boyutlarının uygunluğunu,  Kilit tertibatı  Emniyet kontağı",
  "İmdat kapağı : 0,40 m x 0,50 m (0,50 x 0,70 m olabilir), İmdat kapısı : 0,40*1,8 m İmdat kapağı/kapısı boyutları: (G):………......cm, (Y):……........cm",
  "Kabinin en az bir yan duvarına tutamak uygunluğu Camları, zeminden 1,10 m yükseklikten daha aşağıda yerleştirilmiş olan kabin duvarlarında 0,90 m ile 1,10 m arasında yükseklikte bir korkuluk bulunmalıdır. Bu korkuluk camdan bağımsız olarak sabitlenmelidir. Yarıçapı en az 10 mm kesiti 30-45 mm, , duvar ile kavranan bölüm arası 35 mm, tutamak yüksekliği 850±25 mm",
  "Kabin buton yerleşim uygunluğu",
  "a) İmdat ve kapı butonlarının merkez hattı kabin tabanından en az h > 850 mm yerleşimi, en fazla h<1200 mm b) Çağrı butonları imdat ve kapı butonlarının üstünde yerleştirilmeli c) Tek yatay sıra için çağrı butonları sıralaması soldan sağa, tek düşey sıra için alttan üste, birden fazla düşey sıra için önce soldan sağa sonra alttan üste doğru yerleştirilmeli d) Herhangi bir buton merkezi ile kabin duvarı arası mesafe en az 400 mm olmalı",
  "Kabin kumanda paneli kabin duvara yerleşimi",
  "a) Ortadan açılan kapılı asansörlerde, kabine girerken sağ tarafta, b) Yana açılan kapılı asansörlerde, kapının kapanma kenarı tarafında. c) kabin genişliği 1 600 mm'yi aştığında kabinin her iki yan duvarı üzerinde de bir kabin işletim paneli olmalıdır; d) bitişik kapıları olan kabinlerde, kabinin kapı olmayan her duvarı üzerinde bir kabin işletim paneli olmalıdır.",
  "Kabin içinde kullanılacak ayna koşullarının uygunluğu",
  "Işık kaynaklarının yansımasından kaynaklanan yansımaları, optik karmaşaları ve kamaşmaları önlemek için duvarların mat yüzeylere sahip olması tavsiye edilir. Kabinin herhangi bir duvarı büyük ölçüde aynayla donatılacaksa, camın dekore edilmiş olması ya da zemin ile aynanın taban kenarı arasında düşeyde asgari 300 mm'lik bir mesafe olması tavsiye edilir.",
  "Durak kapı yüksekliği ve genişliğinin uygunluğu",
  "Durak kapılarının serbest yüksekliklerinin en az 2 m ve serbest genişlikleri, kabin kapısı genişliğinin her iki yanda ayrı ayrı olmak üzere 50 mm’den fazla aşmadığını teyit ediniz.",
  "Kuyu duvarlarındaki asansör kabinine girişi sağlayan açıklıklara, yüzeyleri deliksiz olan durak kapıları konulması",
  "Kapı kapalı durumda iken kapı kanatları veya kanatlar ile kasa, eşik veya kasa üstü arasındaki açıklıklar mümkün olduğu kadar küçük olduğunu teyit ediniz. Not: Bu açıklıklar 6 mm’yi geçmediğinde bu şart yerine getirilmiş sayılır.",
  "Kabinin yüklenme ve boşaltılması için yeterli dayanıma sahip bir eşik bulunması",
  "Durak kapılarının kılavuzlarının uygunluğu ve yeterli dayanımı",
  "Kabin kapısı ile durak kapısı arası mesafe uygunluğu ( ≤ 0,15 m)",
  "Menteşeli kat kapısı ile kabin kapısı arası 0,12 m - Otomatik tak kapısı ile kabin kapısı arası 0,15 m",
  "5 cm2 300 N uygulandığında 1 mm kalıcı şekil değişikliği, 15 mm elastik şekil değiştirme 100 cm2 1000 N uygulandığında kalıcı şekil değiştirmenin olmaması Cam Panel olması halinde TS EN 81-20 Madde 5.3.5.3.4. şartları aranır.",
  "Makina gücü ile çalışan menteşeli kapılar için açılıp kapanırken insanlara çarpma riski var ise, önlemler alınması",
  "Sahanlık aydınlatması ….........................lüks (Döşeme seviyesindeki x> 50 lüks)",
  "Elle açılan durak kapılarında, kullanıcının kapıyı açmadan önce, kabinin katta olup olmadığını anlayabilmesi",
  "Kat kapı kilit dili en az 7 mm olmalı",
  "Her durak kapısında kapının kapandığını denetleyen emniyet kontağı bulunması (fiş-priz bağlantısı)",
  "Durak kapısı açık veya kilitli olmadığında asansörün çalıştırılamaması (Durak kapı kilitlerine erişimde kontrol edilmelidir.)  By-pass tertibatının uygunluğu (Kabin ve Kat kapıları için)",
  "Sürmeli kat kapılarının mekanik bağlantılı çok sayıda paneli varsa standardın şartlarının yerine getirilmesi",
  "Park ederken durak kapılarının kapanması",
  "Tüm kat kapı topraklama bağlantı uygunluğu",
  "Kabinin durağı terk etmesi en az 2 sn engellenmelidir. Kapı kapalı dış buton iç buton kaydından 2 sn sonar kayıt alabilmelidir. Ortak kumandalı asansörlerde ışıklı ikaz ile hareket yönü belirtilmelidir.",
  "Kapı açılması sesli ikazı 45 dB (A) ve üzeri olmalı",
  "Kabine girmeden önce, kumanda sistemi yeni seyir yönünü belirliyorsa (müşterek kumanda) aydınlatılmış işaret okları kapının üstüne veya yakınına yerleşimi",
  "İşaret okları zeminden 1,80-2,5 yukarıda, durak tarafından görüş açısı 140o olacak şekilde konumlandırılmalı, ok yükseklikleri 40 mm olmalı, sesli işaret okların aydınlatması ile birlikte verilmeli, yukarı ve aşağı için farklı sesli işaretleri kullanılmalı (yukarı için bir ses, aşağı için iki ses)",
  "Kat butonlarının montaj ve çalışması (varsa) topraklama bağlantısı",
  "a) Butonlarının merkez hattı kat hizasından en az h > 850 mm yerleşimi, en fazla h<1100 mm b) Buton merkezi ile kat sahanlığı yan duvar arası açıklık mesafesi en az 500 mm olmalı",
  "TS EN 81-73 Md. 5.1.6 BYKHY Madde 62",
  "Yangın anında kullanmayınız bilgi etiketi bulunması",
  "Tüm kat kapılarının olduğu katlarda yer almalıdır.",
  "Kabin üst işaretlemeleri, temizliği",
  "Kabin üstünün bir yerinde, durmak için en az 0,12 m² büyüklüğünde serbest bir alan bulunması (Bu alanın en küçük kenarı en az 0,25 m olmalıdır.)",
  "0,30 m x 0,30 m lik bir alanda 2000 N kuvvete dayanabilmelidir.",
  "Korkuluk ve uyarı işaretlemesi a) 0,30 < x < 0,50 m’den büyük en az 0,7 m, b) 0,50 m’den büyük en az 1,1 m olmalı",
  "10 cm yüksekliğinde ayak koruyucu ve kabin tavanının kenarından en fazla 15 cm mesafede olmalıdır.",
  "Kork. Boyu (L): …..........cm Arka….......... cm Sol Yan…...........cm Sağ Yan…............cm",
  "Kabin üstü cam kullanılmış ise lamine cam olması",
  "Kabin iskeletine monte edilmiş saptırma kasnaklarının uygun koruma tertibatı, halat atma pimi takılması",
  "Halat Çapı / Kasnak Çapı (x > 1/40) ………. / ……….",
  "Kuyudaki çıkıntı veya kiriş olması",
  "kabin üst korkuluğu ile erişim engellenmediği sürece, 15 cm’den fazla çıkıntılar 45o ile pahlanmış olmalı",
  "Asansör kuyu duvarlarının ve kabin girişine bakan durak kapılarının yapımının standarda uygunluğu",
  "X < 0,15 m (kısmi ise X < 0,20 * 0,50 m) Kabin ve kat kapı panelleri arası 0,12 m aşmamalı.",
  " Kumanda tertibatı,  Acil aydınlatma…................lüks  Durdurma tertibatı,  Priz,  Alarm / Haberleşme",
  "Aşağı-yukarı yön, hareket, kumanda anahtarı, işaretleme, Kabin üstü merkezinden 1 m üstünde x > 5 lüks olmalı, Kapı girişinden en fazla 1 m mesafede konumlanmalı 220 V ve topraklama bağlantısı kontrol edilmeli Kabin üstü merkezinden 1 m üstünde yerleştirilmeli",
  "Kabin ve kabine bağlı parçalar ile K./D. ağırlık arası açıklık …..........................mm (x > en az 50 mm)",
  "Kabin, karşı ağırlık ve (varsa) dengeleme ağırlıklarının halat bağlantıları (Halat soketleri, Halat klemensleri) uygunluğu",
  "Halat çapı en az 8 mm ve en az 2 adet olmalı, İlk klemens en az kama boyunun %40’ından daha fazla olmamalıdır. (Simetrik soket) İlk klemens en az kama boyunun %75’inden daha fazla olmamalıdır. (Asimetrik soket)",
  "Karşı ağırlık sıçrama önleyici tedbir",
  "Kat kapı kilitlerinin ve elektriksel denetim uygunluğu",
  "Kilit açılma bölgesi en fazla 0,20 m olmalıdır. Kabin ve kat kapıları birlikte çalıştırılması halinde 0,35 m ye kadar uzanabilir.",
  "Kapasite (P+Q): …...............(kg)",
  "Kapasite (P+Q): …….……......(kg)",
  "Yukarı yönde hareket eden kabinin aşırı hızlanmasına karşı korumanın uygunluğu",
  "Elektrikli asansör için İmalatçi bilgisi / Tip inceleme belge no / devreye grime hızı / tipi",
  "Yavaşlatma sistemi uygunluğu…...........cm",
  "2,5m/s ‘nin üzerindeki anma hızlarında ölçüm yapılır.",
  " Alt Sınır Kesici …..................cm",
  "Hidrolik ise sadece üst sınır kesici takılmalı ve kilitlemeli olmalı",
  " Üst Sınır Kesici …..................cm",
  "Kabin üstü / karşı ağırlık / dengeleme ağırlığı / piston üstü kasnakların montaj uygunluğu",
  "Kasnak koruma / halat atma / yabancı cisim girme durumu",
  "Kabin için monte edilen hız regülatörünün uygunluğu",
  " Halat çapı  Hız regülatörüne erişim  Mühür  Emniyet Kontağı  Kasnak koruma, halat atma pimi",
  "Dengeleme ağırlığı için monte edilen hız regülatörünün uygunluğu",
  "Karşı ağırlık tam kapanmış tampon üzerinde otururken, dört şart yerine getirilmesi",
  "(i) ............m (Ray Uzunluğu > 0,10 m, Ray korkuluk arası en az 10 cm olmalıdır) ) (- M çıkarılacaktır) (ii)............m (korkuluk – tavan arası > 0,30 m) ) (- M çıkarılacaktır) (iii)............m (Kabin üstü – tavan altı arası > 1,00 m ) ) (- M çıkarılacaktır) (iv)...........m (Tavan - kılavuz paten veya makaraların, halat bağlantılarının veya kabin üstü siperinin veya düşey sürgü kapı",
  "M: Düşülecek mesafe, Y: Eşik arası mesafe, X: Kayma Payı, S: Strok Mesafesini ifade eder. (Ölçüm için 0,0035 V^2(m) sıçrama payı ilavesi edilecektir.)",
  "parçaları > 0,10 m) ) (- M çıkarılacaktır) (iv) (Güvenlik hacmi >  0,40*0,50*2,00 m /  0,50*0,70*1,00 m) ) (- M çıkarılacaktır)",
  "Piston tam açıldığında, kabin üst güvenlik boşluğu altı şartı yerine getirilmesi",
  "(i) ………….… (Ray uzunluğu > 0,1⋅m, Ray korkuluk arası en az 10 cm olmalıdır) ) (ii) ………….… (Kabin üstü – tavan > 0,50 m) (iii) ………….… (Tavan – korkuluk > 0,3 m) (iv) ………….… (Tavan - Paten veya Makaraların, halat bağlantı uçlarının ve başlığın en yüksek kısımları veya düşey sürgü kapı parçaları > 0,1 m) (v) (Güvenlik hacmi > 0,40*0,50*2,00 m / 0,50*0,70*1,00 m) (vi) ………….… (Piston başı – tavan arası > 0,1 m)",
  "Mekanik tertibatın veya hareketli durdurucunun uygunluğu",
  "Güvenlik tertibatının mekanik tertibat olarak kullanıldığı durumlara özellikle dikkat edilmelidir, örneğin, kabin, boşken ve acil durum çalıştırma hızında seyir ederken.",
  " Karşı ağırlık karkas montaj uygunluğu  Kabin üst paten montaj uygunluğu  Karşı / Dengeleme ağırlığı alt/üst paten montaj uygunluğu  Bükülgen kablo (Fleksible) takozu kuyu montaj uygunluğu",
  "Boru kırılma valfinin uygunluğu :….......…..(bar)",
  "İmalatçi bilgisi / Tip inceleme belge no / Ayarlanmış olduğu devreye girme debisi",
  "Debi Sınırlama valfinin uygunluğu :…...…..(bar)",
  "Kenetleme tertibatının uygunluğu :…....…..(kg)",
  "0,12 m aşağı kaydırmamalı, tamponlama bulunmalı, elektriksel denetim olmalı",
  "Teleskopik kaldırıcılar için gerekli şartları teyit ediniz. Silindirlerin birbirinden ayrılmasını engelleyecek şekilde kademeli olmalı, Kabin tam kapanmış tampon üzerinde bulunuyorken, direk tahrikli bir asansör kabininin altına yerleştirilen bir hidrolik kaldırma ünitesi arasında, en üst kılavuz taşıma çatalı ile taşıma taşıma çatalının dikey çıkıntısından itibaren 0,30 m bir yatay mesafe içerisinde kabinin en alt parçaları arasında en az 0,30 m mesafeler olmalıdır.",
  "Makine/ makara mekânlarına erişimin şahıslar için güvenli olduğu (Bu erişim tercihen merdivenlerle sağlanmalıdır.)",
  "Makine Dairesi yangına 60 dk dayanıklı malzemeden yapılmalı",
  "Birden fazla asansör var ise işaretlenmeli ve ayırt edilebilmeli",
  "Makina dairesi güvenlik işaretlemeleri",
  "Kapı, elektrik ve kumanda panosu, risk analizi sonrası, vs.",
  "Makinanın maruz kalacağı yük ve kuvvetlere dayanımı",
  " Kilitlenebilir Ana Şalter  IP2X,  Topraklama Tesisatı",
  " Aydınlatma ve Priz Sigortaları: (Kuyu: ….........A, Kabin……........A, M.Dairesi…...........A)  Motor Beslemesi için 4 lü grup sigorta:…….....A, KAR…….........A, …...............mA",
  " Aydınlatma ve Priz için işaretleme ile KAR….................A, …….............mA (30mA olmalı)",
  "Makina Dairelerindeki Makinalar",
  "Tahrik kasnağı kuyu içine tesis edildiğinde uygunluğu",
  "Makina dairesinin projeye uygunluğu",
  " Kilit Sistemi  Döşeme delikleri (50 mm)  Havalandırma  Aydınlatma Anahtarı  Topraklı Priz  Kanca (kapasite, montaj)",
  "Makine dairesi aydınlatma şiddeti:……............lüks",
  "Kapı / Kapak Ölçüsü:…..............m (en-boy) (Kapı boyutları en az 0,6*2,0 m, Döşeme Kapağı boyutları en az 0,8*0,8 m)",
  " Çalışma alanı uygunluğu  Serbest yükseklik  Dönen aksamın üstündeki mesafe (en az 30 cm)  Merdiven, korkuluk  Kurtarma Talimatı  Halat kat işaretlemesi  Volan Yön İşaretlemesi",
  "Kurtarma Talimatı üçgen anahtar kullanımını da içermeli veya ayrı bir talimat bulunmalıdır. Geçiş Yolu Yüksekliği: ………………… cm Çalışma Alanı Yüksekliği: ……………… cm",
  "Kumanda Panosunun sabitlenmesi ve bağlantılarının uygunluğu (IP2X)",
  "Emniyet devreleri için KAR uygunluğu (30 mA olmalıdır.)",
  "Emniyet devreleri IP 4X uygunluğu",
  "Asansör Kuyusu İçindeki Makinalar",
  "Makina mekanının projeye uygunluğu",
  " Çalışma alanı uygunluğu  Mekanik tertibat  Serbest yükseklik (en az 2,1 m)  Test Düzeneği  Bakım kapısı/kapağı (kilit, emniyet kontağı)  Havalandırma  Kanca (kapasite, montaj)  Topraklı Priz  Aydınlatma Anahtarı",
  " Geçiş yüksekliği (en az 1,8 m)  Dönen aksamın üstündeki mesafe (en az 30 cm)  Kurtarma Talimatı Çalışma alanında aydınlatma şiddeti: …..............lüks (en az 200 lüks) Test düzeneği önünde aydınlatma:…..................lüks (en az 50 lüks)",
  " Kapı / Kapak uygunluğu (deliksiz, kilit, emniyet kontağı)",
  "Kapı / Kapak Ölçüsü:…...................m (en-boy)",
  "(Kapı boyutları en az 0,6*2,0 m, Döşeme Kapağı boyutları en az 0,8*0,8 m)",
  "Makina kuyu içerisinde bulunuyor ve bakımının / muayenesinin kuyu dışından yapılabilmesi",
  " Çalışma alanı uygunluğu  Serbest yükseklik (2,0 m)  Kapı (0,6*2,0 m)  Döşeme Kapağı (0,8*0,8 m)",
  "Platform Üzerindeki Çalışma Alanları",
  "Kalıcı monte, seyir halinde geri çekilebilir ve hareketli durdurucu",
  "Platformun standarda uygunluğu",
  " Test Düzeneği  Bakımcı Kumandası",
  "Çalışma alanında aydınlatma:….........… lüks (en az 200 lüks)",
  " Hareketli durdurucu  Platform Kapasite Etiketi",
  "Test düzeneği önünde aydınlatma:……........lüks (en az 50 lüks)",
  "Asansör makinasının asansörden başka hiçbir şey için kullanılmayan bir dolabın içine yerleştirilmesi",
  "Bu dolap asansörden başka boru, kablo ve diğer teçhizatları bulundurmamalıdır.",
  "Deliksiz duvar, döşeme, tavan ve kapı",
  " Çalışma alanı uygunluğu  Havalandırma  Aydınlatma anahtarı",
  "Çalışma alanında aydınlatma şiddeti :…............ lüks (en az 200 lüks) Kapı Ölçüsü:…............m (en-boy) (Kapı boyutları en az 0,6*2,0 m)",
  " Kilit Sistemi  Topraklı Priz",
  "Kabin hız regülatörünün uygunluğu",
  "K. Ağırlık / D. Ağırlığı hız regülatörünün uygunluğu",
  "Makine / Şase montaj uygunluğu (şase bağlantısı, mil, yan yatak, dişli sistemi, yağlama, temizlik, ses, titreşim, kayış, deformasyon, çatlak)",
  "Motor montajı uygunluğu (fan, elektrik beslemesi ve topraklama bağlantısı)",
  "Fren kolu, volan, balatalar, bağlantı tiji",
  "Tahrik ve Saptırma Kasnakları için:",
  " Dur Butonu  Halat uç bağlantıları  Halat yük dengesi  Kasnak korumaları",
  " Halat atma pimi  Saptırma Kasnağı ve montajı/Halat/Çap oranı < 1/40, 2 halat kullanılmışsa emniyet kontağı kullanılmalıdır.",
  " Dönen aksamın üstündeki mesafe (en az 30 cm)  Havalandırma  Aydınlatma (en az 200 lüks)  Topraklı Priz  Serbest yükseklik (1,5 m)  Döşeme delikleri (50 mm)",
  " Kapı(0,6*1,4 m)  Kilit Sistemi",
  " Döşeme Kapağı (0,8*0,8 m)  Çalışma alanı uygunluğu(50*60 cm)",
  "Çalışma alanında aydınlatma şiddeti:…..................lüks",
  "(en az 200 lüks) Geçiş Yolu Yüksekliği:…................ Cm",
  " Silindir kafasından kaçak ve sızan hidrolik sıvısı toplanabilmeli,",
  " Havalandırma tertibatı bulunmalı",
  "Hortum bağlantılarının uygunluğu (Güvenlik katsayısı 8, tam yük basıncının 5 katına dayanıklı, bükülme yarıçapı uygun, imalatçı adı veya markası, deney basıncı, deney tarihi olmalı)",
  "Boruların uygunluğu (Tespit yerleri, burulma veya titreşim nedeniyle normal olmayan bir gerilmeye maruz kalmamalı, mekanik hasara karşı korunmalı, Tam yük basıncının 2,3 katına tekabül eden, 1,7 güvenlik katsayısında olan)",
  "Filtrelerin uygunluğu (Erişilebilirlik, tank ve pompa ile kapama vanası, geri dönüşsüz vana ve aşağı yön vanası arası)",
  "Manometre bulunmalı (Bağlantı geri dönüşsüz vana veya aşağı yön vana ile kapama vanası arasında ve bağlantı M20 x 1,5 veya G ½” lik bir iç vida dişile sağlanmalı)",
  "Tank üzerinde; hidrolik sıvı seviyesi kolayca kontrol edilebilmeli, doldurmak ve boşaltmak kolay olmalı Tank üzerindeki hidrolik sıvı karakteristikleri göstermelidir.",
  "Acil iniş vanası çalışma uygunluğu Makina dairesi veya Makina dolabı veya Acil durum deney panosu üzerinde, hız 0,30 m/s aşmamalı, sürekli el ile kuvvet uygulanarak çalışmalı, istemdışı kabin hareketine karşı korunmalı, işaretlemeli, halat/zincir gevşememeli",
  "El pompası çalışma uygunluğu Tam yük basıncının 2,3 katı basınca dayanıklı, geri dönüşsüz vana veya aşağı yön vanası veya kapatma vanası arasına bağlanmalı, işaretleme olmalı",
  "Kabin pozisyon göstergesi (Makina dairesi veya Makina dolabı veya Acil durum deney panosu üzerinde)",
  "Kabinin ara katlarda her iki yönde ve bütün duraklarda durma ve seviyeleme hassasiyeti (Kabinin durma hassasiyeti ± 10 mm olmalıdır, ± 20 mm lik seviyeleme hassasiyeti korunmalıdır.Kabinin örneğin yükleme ve boşaltılma safhaları sırasında 20 mm aşılırsa, bu düzeltilmelidir.)",
  "Motor hareket süresi sınırlayıcısı",
  "En uzun kat arası mesafede test edilir, Parametre ayarlarının uygunluğu kontrol edilir.",
  " PTC,  Kontaktör  Faz sıralı koruma rölesi",
  "By-pass tertibatının uygunluğu",
  "Kontrol veya acil durum ve deney panelinde bulunmalı, işaretlenmeli, korumalı olmalı",
  "Kapı kontakları köprüleme kontrolü",
  "Fren tertibatının (Elektromekanik fren) uygunluğu Deney, beyan yükünün % 125’i ile yüklü kabin aşağı yönde hareket ederken motora ve frene giden enerjinin kesilmesi suretiyle yapılmalıdır. Fren tamburu veya diski üzerindeki frenleme etkisinin sağlanmasına katkıda bulunan, frene ait mekanik parçaların bobin haricinde tümü ikişer adet olmalıdır. Parçalardan birinin devre dışı kalması durumunda (tek çene) dahi, aşağı yönde hareket eden ve beyan yükü ile yüklü kabini güvenlikle durduracak ölçüde frenleme etkisi sağlanmalıdır",
  "Tahrik yeteneğinin uygunluğu 1) Seyir mesafesinin üst kısımlarında, boş kabin yukarı çıkarken veya seyir mesafesinin alt kısımlarında, % 125 beyan yükü ile yüklü kabin aşağı inerken yapılmalıdır;",
  "2) Karşı ağırlık tam kapalı tamponlar üstünde oturduğunda, boş kabinin yukarı kaldırılamayacağı kontrol edilmelidir, ya da makine 5.11.2’ye uygun emniyet kontağı ile durdurulmalıdır. 3) Karşı ağırlık dengelemesinin asansör imalâtçısının verdiği değerlere uygunluğu kontrol edilmelidir, bu kontrol aşağıda belirtilenlerle birlikte akım ölçümleri vasıtasıyla yapılabilir: a) Alternatif akım motorlarında hız ölçümleriyle, b) Doğru akım motorlarında gerilim ölçümleriyle.",
  "Kabin güvenlik tertibatı uygunluğu 1) Ani frenlemeli güvenlik tertibatı: Kabin beyan yükü ile yüklü ve beyan hızıyla, 2) Kaymalı güvenlik tertibatı: Kabin %125 beyan yükü ile yüklü ve beyan hızı veya daha düşük bir hızla",
  "Kabin döşemesinin eğilmesi (Güvenlik aygıtları devreye girdiğinde, üzerindeki yük eşit olarak dağıtılmış olsun ya da olmasın, kabin zemini normal konumuna göre %5'ten fazla eğimli olmamalıdır.)",
  "Karşı ağırlık veya dengeleme ağırlığı güvenlik tertibatı uygunluğu",
  "Kabinin istemdışı hareketine karşı koruma tertibatı",
  "cm (Boş kabin yukarı yönde) cm (%100 yüklü kabin aşağı yönde)",
  "Hız regülatörünün devreye girmesi Güvenlik tertibatı için hız regülatörü devreye girmesi, aşağıdakilerden küçük olan ve beyan hızının en az % 115’ine eşit bir hızda meydana gelmelidir. Dikkate alınacak hususlar; 1,0 m/s’yi aşmayan beyan hızları için kullanılan kaymalı güvenlik tertibatı için 1,50 m/s veya 1,0 m/s’yi aşan beyan hızlarında kullanılan kademeli bir güvenlik tertibatı için 1,25.v +(0,25/ v) m/s Beyan hızı 1 m/s’yi aşan asansörlerde, 1,25.v +(0,25/ v) m/s (gerekli değere mümkün olduğu kadar yakın devreye girme hızı seçilmesi önerilmektedir. Güvenlik tertibatının çalışması ilgili dönme yönü ile, hız regülatörü üzerinde işaretlenmelidir. Bkz. Madde 81- 50:2014, Madde 5.3.2.3.1), regülatör üzerindeki devreye girme noktaları arasındaki mesafe, regülatör halatının hareketine göre 250 mm’yi aşmamalıdır.",
  "Yukarı yönden hareket eden kabinin aşırı hızlanmasına karşı koruma tertibatı / Elektromanyetik fren tertibatı uygunluğu Boş kabin en az beyan hızıyla yukarı yönde hareket ederken yalnız bu tertibatın kullanılmasıyla durdurularak deney yapılmalıdır. Elektromanyetik frenler en az iki adet olmalı ve her biri için elektriksel denetimi yapılmış olmalı ve tekil olarak kontrol edilir. Tekil olarak harekete izin vermemelidir.",
  "Yalıtım dirençlerinin uygunluğunu teyit ediniz. (Not: Emniyet devreleri, Aydınlatma devresi ve Motor devresi için deney gerilimi 500 V olarak uygulanacaktır.) Kapı Fiş-Priz Devresi (gidiş-dönüş) ≥ 1,0 MΩ : …………………  Kapı Kilit Devresi (gidiş-dönüş) ≥ 1,0 MΩ: .................. Stop Devreleri ≥ 1,0 MΩ : ………….………  Sınır Kesici Devreleri ≥ 1,0 MΩ :................... Aydınlatma Devreleri ≥ 1,0 MΩ : ………………….  Motor Devresi ≥ 1,0 MΩ :................... ",
  "Akım veya güç ile hızın ölçüm sonuçlarına göre sistemin tasarım uygunluğu (Hidrolik asansörlerde hız 1,0 m/s geçmemelidir.)",
  "Asansörün Yangın anındaki davranış senaryosu",
  "Yukarı yönde emniyet kontaklarının kontaktörü kesmesi ile Aşağı yönde aşağı yön vanası ile",
  "Kapama vanası fonksiyon uygunluğu Kapama vanası tahrik makinası üzerinde diğer vanalara yakın bir yerde bulunmalıdır.",
  "Asansörde bir kapama vanası bulunmalıdır. Bu vana, silindir (veya silindirler) ile geri dönüşsüz vana ve aşağı yön vana (veya vanaları) arasındaki devreye konulmalıdır.",
  "Geri dönüşsüz vananın fonksiyon uygunluğu Vananın kapanması, kaldırıcının hidrolik basıncı ve en az bir adet kılavuzlanmış yay ve/veya ağırlık kuvveti ile etkili olmalıdır.",
  "Asansörde bir geri dönüşsüz vana bulunmalıdır. Bu vana, pompa (veya pompalar) ile kapama vanası arasındaki devreye konulmalıdır. Pompa basıncının en küçük çalışma basıncının altına düşmesi durumunda beyan yükü ile yüklü kabini her noktada sabit tutabilecek bir kapasiteye sahip olmalıdır.",
  "Basınç sınırlama valfinin doğru ayarlanması",
  "Asansörde bir basınç sınırlama vanası bulunmalıdır. Bu vana, pompa (veya pompalar) ile geri dönüşsüz vana arasındaki devreye konulmalıdır. Hidrolik sıvısı tanka geri sevk edilmelidir. Basınç sınırlama vanası, basınç tam yük basıncının %140’ında sınırlanacağı bir şekilde ayarlanmalıdır.",
  "Esnek durdurucunun fonksiyon uygunluğu",
  "Pistonun tampon etkisiyle durdurulması",
  "Tam yükteki basıncın uygunluğu",
  "P…....................bar (tam yük)",
  "Hidrolik sıvının aşırı ısınmasına karşı dedektör",
  "Yön valflerinin fonksiyon uygunluğu (aşağı – yukarı) Boru kırılma valfinin fonksiyon uygunluğu, Kapasite (bar)",
  "Aşağı yön valfları elektrikle açık tutulmalıdır. Valfların kapanması, kaldırıcının hidrolik basıncı ve valf başına en az bir adet kılavuzlanmış yay etkisi ile olmalıdır.",
  "Boru kırılma valfinin fonksiyon uygunluğu, Kapasite : ……………. (bar) (Boru kırılma valfı, aşağı yönde hareket eden kabini durdurabilmeli ve hareketsiz tutabilmelidir. Boru kırılma valfı en geç aşağı yön beyan hızı vd ’ye, 0,3 m/s ilâvesiyle bulunan hızda devreye girmelidir. Boru kırılma valfı, ayarlama ve muayene için erişilebilir olmalıdır.)",
  "Debi sınırlama valfinin fonksiyon uygunluğu (Debi sınırlama valfı, hidrolik sistemde büyük bir kaçak olduğunda beyan yükü ile yüklü kabinde hızın, aşağı yön beyan hızı vd ’yi 0,3 m/s’den fazla aşmasını engellemelidir. Debi sınırlama valfı muayene için erişilebilir olmalıdır.)",
  "Kayma kontrolü (Beyan yükü ile yüklü ve en üst durakta duran kabinin 10 dakika içinde aşağı doğru 10 mm’den fazla kaymadığı kontrol edilmelidir. )",
  "Basınç deneyi için gerekli standart şartlarının karşılandığını teyit ediniz. (Geri dönüşsüz valftan kaldırıcıya kadar (kaldırıcı dahil) olan hidrolik sisteme, tam yük basıncının %200’ü uygulanmalıdır. Bundan sonra 5 dakika süre ile sistemde basınç düşmesi ve hidrolik kaçağı olup olmadığı gözlenir.) Not - Bu deney, serbest düşmeye karşı tertibatın (Madde 9.5) denenmesinden sonra yapılmalıdır.",
  "Kabin %125 beyan yükü ile yüklenmelidir.",
  "TESPİT EDİLEN BULGULAR: …………………………………………………………………………………..……………………………………………………………………………………..….……………………………………………………………………………………………………………………………………………………………………………………..................................................................................................................................................................................................................................................................................................................................……………………………………………………………………………………………………………………………………………………………………………………………..............................................................................................................................................................................................................................................................…..………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………....................................................................................................................................................................................."
];
